struct WearableParams
{
	Name WorldItemCls;
	Name WornItemCls;
	string LanguagePrefix;
	string SoundPrefix;

	class<Inventory> GetWorldItem()
	{
		return WorldItemCls;
	}
	class<Inventory> GetWornItem()
	{
		return WornItemCls;
	}
}

extend class HDFollower
{
	// --------------------------------------------------
	// ACTIONS
	// --------------------------------------------------

	private void LookForWearable()
	{
		if (!WearableInfo.GetWorldItem() || !WearableInfo.GetWornItem())
		{
			return;
		}

		if (Distance3D(LinkedPlayer) > MaxWaitRange)
		{
			PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_RANAWAY"), WearableInfo.SoundPrefix.."/RanAway", PMType_Critical);
			Status = FStatus_None;
			tracer = null;
			return;
		}

		CheckProximity(WearableInfo.worldItemCls, radius + MaxSearchRange, 1, CPXF_ANCESTOR|CPXF_CLOSEST|CPXF_SETTRACER);
		let foundWearable = Inventory(tracer);
		let wornWearable = FindInventory(WearableInfo.WornItemCls, true);

		let hw = HDWeapon(foundWearable);
		let hp = HDPickup(foundWearable);

		if (foundWearable)
		{
			if (!wornWearable)
			{
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NONE"), WearableInfo.SoundPrefix.."/None", PMType_General);
			}
			else if (wornWearable is 'HDArmourWorn')
			{
				let foundArmor = HDArmour(foundWearable);
				let wornArmor = HDArmourWorn(wornWearable);

				// [Ace] 1030 because mega armor's durability is calculated as 1000 + actual durability. Only while on the ground, though.
				// [UZ] 2026-04-21: Armour Refactor removed "mega" property, now split into individual actors
				//   TODO: Generify Armor Preference/Priority
				//   For Now, simply replace via scaled durability
				if (((1.0 * wornArmor.Durability) / wornArmor.default.Durability) < ((1.0 * foundArmor.Mags[foundArmor.Mags.Size() - 1]) / foundArmor.maxperunit))
				{
					PrintMessage(GetResponse("ARMORGIVE_BETTERDURABILITY"), "ArmorGive/BetterDurability", PMType_General);
				}
				else
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
					Status = FStatus_None;
					tracer = null;
					return;
				}
			}
			else
			{
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
				Status = FStatus_None;
				tracer = null;
				return;
			}

			if ((hp && hp.wornlayer > 0) || (hw && hw.wornlayer > 0)) while (!HDPlayerPawn.CheckStrip(self, foundWearable));
			
			if (hw)
			{
				hw.ActualPickup(self);
			}
			else if (hp)
			{
				hp.ActualPickup(self);
				UseInventory(FindInventory(foundWearable.GetClass()));
			}
			Status = FStatus_None;
		}
		tracer = null;
	}
	
	void TryUseWearable()
	{

		if (!WearableInfo.GetWorldItem() || !WearableInfo.GetWornItem()) return;

		switch (Status) {
			case FStatus_InactiveOrDead:
				// no-op
				break;
			case FStatus_WaitingForWearable:
			
				CheckProximity('HDArmour', radius + 24, 1, CPXF_ANCESTOR|CPXF_CLOSEST|CPXF_SETTRACER);
				let FoundArmor = HDArmour(tracer);
				let WornArmor = HDArmourWorn(FindInventory('HDArmourWorn', true));

				CheckProximity('HDStorageItem', radius + 24, 1, CPXF_ANCESTOR|CPXF_CLOSEST|CPXF_SETTRACER);
				let FoundBackpack = HDStorageItem(tracer);
				let WornBackpack = HDStorageItem(FindInventory('HDStorageItem', true));

				CheckProximity('Shieldcore', radius + 24, 1, CPXF_CLOSEST|CPXF_SETTRACER);
				let FoundShield = Shieldcore(tracer);
				let WornShield = HDMagicShield(FindInventory('HDMagicShield'));

				if (FoundArmor)
				{
					if (WornArmor)
					{
						// [Ace] 1030 because mega armor's durability is calculated as 1000 + actual durability. Only while on the ground, though.
						// [UZ] 2026-04-21: Armour Refactor removed "mega" property, now split into individual actors
						//   TODO: Generify Armor Preference/Priority
						//   For Now, simply replace via scaled durability
						if (((1.0 * WornArmor.Durability) / WornArmor.default.Durability) < ((1.0 * FoundArmor.Mags[FoundArmor.Mags.Size() - 1]) / FoundArmor.maxperunit))
						{
							PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_BETTERDURABILITY"), WearableInfo.SoundPrefix.."/BetterDurability", PMType_General);

							A_DropInventory(WornArmor.GetClass());
						}
						else
						{
							PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
							Status = FStatus_None;
							tracer = null;
							return;
						}
					}
					else
					{
						PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NONE"), WearableInfo.SoundPrefix.."/None", PMType_General);
					}


					FoundArmor.ActualPickup(self);
					if (FoundArmor.bDROPTRANSLATION) FoundArmor.translation = translation;
					UseInventory(FoundArmor);
					Status = FStatus_None;
					return;
				}
				else if (FoundBackpack)
				{
					if (WornBackpack)
					{
						PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_CANCEL"), WearableInfo.SoundPrefix.."/Cancel", PMType_Important);
						Status = FStatus_None;
						tracer = null;
						return;
					}
					else
					{
						PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NONE"), WearableInfo.SoundPrefix.."/None", PMType_General);
					}

					FoundBackpack.ActualPickup(self);
					Status = FStatus_None;
					return;
				}
				else if (FoundShield)
				{
					if (WornShield)
					{
						if (FoundShield.mags[FoundShield.mags.size() - 1] > WornShield.amount)
						{
							PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_BETTERDURABILITY"), WearableInfo.SoundPrefix.."/BetterDurability", PMType_General);
							
							A_DropInventory(WornShield.GetClass());
						}
						else
						{
							PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
							Status = FStatus_None;
							tracer = null;
							return;
						}
					}
					else
					{
						PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NONE"), WearableInfo.SoundPrefix.."/None", PMType_General);
					}

					FoundShield.ActualPickup(self);
					UseInventory(FoundShield);
					Status = FStatus_None;
					return;
				}
				else
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_CANCEL"), WearableInfo.SoundPrefix.."/Cancel", PMType_Important);
				}

				tracer = null;
				Status = FStatus_None;
				break;
			default:
				Status = FStatus_WaitingForWearable;
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_INIT"), WearableInfo.SoundPrefix.."/Init", PMType_Important);
				break;
		}
	}

	void DropWearable()
	{
		if (Status == FStatus_InactiveOrDead || !WearableInfo.GetWorldItem() || !WearableInfo.GetWornItem())
		{
			return;
		}

		let wornItem = FindInventory(WearableInfo.WornItemCls, true);
		if (wornItem)
		{
			A_DropInventory(wornItem.GetClass());
			PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_STRIP"), WearableInfo.SoundPrefix.."/Strip", PMType_General);
			Status = FStatus_None;
		}
	}

	// --------------------------------------------------
	// VARIABLES
	// --------------------------------------------------

	WearableParams WearableInfo;
}
