struct WearableParams
{
	Name WorldItemCls;
	Name WornItemCls;
	string LanguagePrefix;
	string SoundPrefix;

	class<Inventory> GetWorldItem()
	{
		return WorldItemCls;
	}
	class<Inventory> GetWornItem()
	{
		return WornItemCls;
	}
}

extend class HDFollower
{
	// --------------------------------------------------
	// ACTIONS
	// --------------------------------------------------

	private void LookForWearable()
	{
		HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Looking For Wearable...");

		if (!WearableInfo.GetWorldItem() || !WearableInfo.GetWornItem())
		{
			HDCore.log("Follower."..getClassName(), LOGGING_WARN, "Invalid WorldItem or WornItem.");

			return;
		}

		if (Distance3D(LinkedPlayer) > MaxWaitRange)
		{
			PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_RANAWAY"), WearableInfo.SoundPrefix.."/RanAway", PMType_Critical);
			Status = FStatus_None;
			tracer = null;
			return;
		}

		CheckProximity(WearableInfo.worldItemCls, radius + MaxSearchRange, 1, CPXF_ANCESTOR|CPXF_CLOSEST|CPXF_SETTRACER);
		let foundWearable = Inventory(tracer);
		let wornWearable = FindInventory(WearableInfo.WornItemCls, true);

		if (foundWearable)
		{
			HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Found Wearable: '"..foundWearable.getClassName().."'");

			let ha = HDArmour(foundWearable);
			let hm = HDMagAmmo(foundWearable);

			int haWornLayer;

			if (ha) {
				let haWornCls  = (Class<Actor>)(ha.wornName());
				let haWornDefs = GetDefaultByType(haWornCls);
				haWornLayer    = HDArmourWorn(haWornDefs).wornlayer;
			}

			if (!wornWearable)
			{
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NONE"), WearableInfo.SoundPrefix.."/None", PMType_General);
			}
			else if (HDCore.isChildClass(foundWearable.getClass(), 'VirShieldBadge') && HDCore.isChildClass(wornWearable.getClass(), 'VirWeakShields'))
			{
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
				Status = FStatus_None;
				tracer = null;
				return;
			}
			else if (HDCore.isChildClass(foundWearable.getClass(), 'ShieldCore') && HDCore.isChildClass(wornWearable.getClass(), 'HDMagicShield'))
			{
				if (wornWearable.amount < hm.mags[hm.mags.size() - 1])
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_BETTERDURABILITY"), WearableInfo.SoundPrefix.."/BetterDurability", PMType_General);
				}
				else
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
					Status = FStatus_None;
					tracer = null;
					return;
				}
			}
			else if (HDCore.isChildClass(wornWearable.getClass(), 'HDArmourWorn'))
			{
				HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Wearing Armor: '"..wornWearable.getClassName().."'");

				// Loop through all possible instances of HDArmourWorn,
				// in case the order in which they're in the Follower's inventory
				// causes HHelmet to be selected first before any others,
				// invalidating the checks below
				HDArmourWorn wearableSameWornLayer;
				HDArmourWorn wearableHighestLayer;
				for (let i = inv; i; i = i.inv)
				{
					if (HDCore.isChildClass(i.getClass(), 'HDArmourWorn'))
					{
						let w = HDArmourWorn(i);

						if (w.wornLayer > 0)
						{
							if (w.wornLayer == haWornLayer) wearableSameWornLayer = w;

							if (!wearableHighestLayer || w.wornLayer > wearableHighestLayer.wornLayer) wearableHighestLayer = w;
						}
					}

					if (wearableSameWornLayer && wearableHighestLayer) break;
				}

				if (wearableSameWornLayer) HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Wearing '"..wearableSameWornLayer.getClassName().."' on same layer ("..wearableSameWornLayer.wornlayer..")...");
				if (wearableHighestLayer)  HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Wearing '"..wearableHighestLayer.getClassName().."' at outermost layer ("..wearableHighestLayer.wornlayer..")...");

				if (wearableHighestLayer && haWornLayer > wearableHighestLayer.wornLayer)
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_WORNOVER"), WearableInfo.SoundPrefix.."/WornOver", PMType_General);
				}
				else if (wearableSameWornLayer && ((1.0 * wearableSameWornLayer.Durability) / wearableSameWornLayer.default.Durability) < ((1.0 * ha.Mags[ha.Mags.Size() - 1]) / ha.maxperunit))
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_BETTERDURABILITY"), WearableInfo.SoundPrefix.."/BetterDurability", PMType_General);
				}
				else if (ha.wornLayer > 0)
				{
					PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
					Status = FStatus_None;
					tracer = null;
					return;
				}
			}
			else
			{
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_NOTHANKS"), WearableInfo.SoundPrefix.."/NoThanks", PMType_Important);
				Status = FStatus_None;
				tracer = null;
				return;
			}

			let hw = HDWeapon(foundWearable);
			let hp = HDPickup(foundWearable);

			if ((ha && haWornLayer > 0) || (hp && hp.wornlayer > 0) || (hw && hw.wornlayer > 0)) {
				let tempWornLayer = ha ? ha.wornLayer : 1;

				if (ha && haWornLayer != tempWornLayer) ha.wornLayer = haWornLayer;

				while (!HDPlayerPawn.CheckStrip(self, foundWearable)) HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Stripping Wearable.");

				if (ha) ha.wornLayer = tempWornLayer;
			}
			
			if (hw)
			{
				HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Giving HDWeapon Wearable.");
				hw.ActualPickup(self);
			}
			else if (hm)
			{
				if (HDCore.isChildClass(hm.getClass(), 'VirShieldBadge'))
				{
					HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Giving Shield Badge.");

					name shieldName = 'VirWeakShields';

					HDF.Give(self, shieldName);
					let sss = HDPickup(FindInventory(shieldName));
					if (sss)
					{
						sss.amount = 1;
						sss.maxamount = hm.mags[hm.mags.size() - 1];
						sss.bulk = hm.magBulk;
						sss.mass = sss.maxAmount - 1;
						sss.bQUICKTORETALIATE = false;

						// if (sss.amount > 0) VirWeakShields.FlashSparks(self);
						if (sss.amount > 0) HDMagicShield.FlashSparks(self);
					}

					hm.destroy();
				}
				else if (HDCore.isChildClass(hm.getClass(), 'ShieldCore'))
				{
					HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Giving ShieldCore.");

					HDF.Give(self, "HDMagicShield");
					let sss = HDPickup(FindInventory("HDMagicShield"));
					if (sss)
					{
						sss.amount = 1;
						sss.maxamount = hm.mags[hm.mags.size() - 1];
						sss.bulk = hm.magBulk;
						sss.mass = sss.maxAmount - 1;
						sss.bQUICKTORETALIATE = false;

						if (sss.amount > 0) HDMagicShield.FlashSparks(self);
					}

					hm.destroy();
				}
				else if (HDCore.isChildClass(hm.getClass(), 'HDArmour'))
				{
					HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Giving HDArmour Wearable.");

					let wornName = HDArmour(hm).wornName();
					HDF.Give(self, wornName);
					let worn = HDArmourWorn(FindInventory(wornName));
					worn.Durability = hm.mags[hm.mags.size() - 1];

					hm.destroy();
				}
				else
				{
					HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Giving HDMagAmmo Wearable.");

					let cls = hm.getClass();
					hm.ActualPickup(self);
					if (!UseInventory(FindInventory(cls))) HDCore.log("Follower."..getClassName(), LOGGING_WARN, "Failed to wear '"..(hm ? hm.getClassName() : cls.getClassName()).."'.");
				}
			}
			else if (hp)
			{
				HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Giving HDPickup Wearble.");

				let cls = hp.getClass();
				hp.ActualPickup(self);
				if (!UseInventory(FindInventory(cls))) HDCore.log("Follower."..getClassName(), LOGGING_WARN, "Failed to wear '"..(hp ? hp.getClassName() : cls.getClassName()).."'.");
			}
			Status = FStatus_None;
		}
		tracer = null;
	}
	
	void TryUseWearable()
	{
		HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Trying to use Wearable...");

		if (!WearableInfo.GetWorldItem() || !WearableInfo.GetWornItem())
		{
			HDCore.log("Follower."..getClassName(), LOGGING_WARN, "Invalid WorldItem or WornItem.");
			return;
		}

		switch (Status) {
			case FStatus_InactiveOrDead:
				HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Can't use, am ded.");
				break;
			case FStatus_WaitingForWearable:
				HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Cancelling waiting for Wearable...");

				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_CANCEL"), WearableInfo.SoundPrefix.."/Cancel", PMType_Important);
				Status = FStatus_None;
				break;
			default:
				HDCore.log("Follower."..getClassName(), LOGGING_DEBUG, "Going to wait for Wearable...");

				Status = FStatus_WaitingForWearable;
				PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_INIT"), WearableInfo.SoundPrefix.."/Init", PMType_Important);
				break;
		}
	}

	void DropWearable()
	{
		if (Status == FStatus_InactiveOrDead || !WearableInfo.GetWorldItem() || !WearableInfo.GetWornItem())
		{
			return;
		}

		let wornItem = FindInventory(WearableInfo.WornItemCls, true);
		if (wornItem)
		{
			A_DropInventory(wornItem.getClass());
			PrintMessage(GetResponse(WearableInfo.LanguagePrefix.."_STRIP"), WearableInfo.SoundPrefix.."/Strip", PMType_General);
			Status = FStatus_None;
		}
	}

	// --------------------------------------------------
	// VARIABLES
	// --------------------------------------------------

	WearableParams WearableInfo;
}
