class RecruitedMarine : HDFollower
{
	Default
	{
		Tag "Marine";
		+HDMOBBASE.HASHELMET
		+HDFOLLOWER.CANDISMISS
		HDFollower.FollowerInfo 100000000, GENDER_MALE, 'FollowerBodyMarine', '';
		HDFollower.ResurrectType RESF_MERCHANT;
	}

	States
	{
		Spawn:
			FLWM A 0;
			Goto Super::Spawn;
	}
}

class FollowerBodyMarine : FollowerBody
{
	Default
	{
		Inventory.MaxAmount 50; // [Ace] Stop hoarding marines, damn it.
		Inventory.Icon "FOLLZ0";
		Tag "Marine";
	}
}